<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Agenda</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">
        
            
        <!-- jquery framework -->
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

        <!-- pillar framework -->
        <script type="text/javascript" src="http://cdn-pillar.s3.amazonaws.com/v2.3/pillar.develop.js?v1.03" app="/modules/app.js?v1" config="/modules/config.js"></script>

        <!-- google style -->
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300' rel='stylesheet' type='text/css'>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <!-- select2 -->
        <script src="lib/select2.js" type="text/javascript" s></script>
        <link href='lib/select2.css' rel='stylesheet' type='text/css'>

    </head>
    <body>

        <?php echo $this->content; ?>     
    
    </body>
</html>